//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/admin/Documents/Projects/Doktr/src/Lifters/Doktr.Lifters.Common/Xml.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Doktr.Xml {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Xml"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IXmlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] Xml.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] Xml.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.prolog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProlog([NotNull] Xml.PrologContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] Xml.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.endElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndElement([NotNull] Xml.EndElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.emptyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyElement([NotNull] Xml.EmptyElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.textElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextElement([NotNull] Xml.TextElementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Begin</c>
	/// labeled alternative in <see cref="Xml.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBegin([NotNull] Xml.BeginContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>End</c>
	/// labeled alternative in <see cref="Xml.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnd([NotNull] Xml.EndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="Xml.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty([NotNull] Xml.EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Text</c>
	/// labeled alternative in <see cref="Xml.node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] Xml.TextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Xml.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit([NotNull] Xml.UnitContext context);
}
} // namespace Doktr.Lifters.Common.XmlDoc.Xml